### ISSUE TITLE
Website base font color is hard to read

### ISSUE THREAD

**Issue by tjantika** [propelorm/propelorm.github.com#343]
The grey base font on the propel2 webpages makes the documentation hard to read especially on not so high quality displays. I suggest the the color would be changed to black. That would mean changing 

body, html {
    color: #444;
 }

to 

body, html {
    color: #000;
 }

in css/layout.css

**Comment by marcj** [comment]
I agree. I was once at a window pc and saw how incredible disgusting their font rendering is. We should fix that.

**Comment by jjok** [comment]
+1 Also, ```code { color:#888; }``` is very hard to read.

**Comment by jjok** [comment]
URGH! I'm on the website again now. SO difficult to read.
+1
