### ISSUE TITLE
I want to build a Chinese version of the document 

### ISSUE THREAD

**Issue by steve-liuxu** [propelorm/propelorm.github.com#391]
Like the title. What should i do?  
In my mind,i should fork the 'master' branch and translate this in my 'zh-cn' branch.

**Comment by robin850** [comment]
HI @steve-liuxu,

Actually I'm not sure we would support this as nobody in the Propel team currently speak Chinese (AFAIK). Thus, it would be hard to sync the English and Chinese versions.

/cc @marcj

**Comment by steve-liuxu** [comment]
@robin850 
My team is working with Propel now. The English version of the document is very unfriendly to interns.
so. I will try it and build a website in my server. I will collect the discuss  and make it better.

Propel is very good,our team hope to be able to contribute to its promotion on China.
